export const movementTasks = [
  'Squat 5 times.',
  'Hop on one leg for 7 seconds.',
  'Touch your toes to the floor and raise your arms up.',
  'Walk 5 steps with your eyes closed.',
  'Turn around 3 times.',
  'Make a “star” with your body for 3 seconds.',
  'Raise your knees high 10 times.',
  'Imagine pulling an invisible rope.',
  'Swing from side to side for 10 seconds.',
  'Take two big steps back and one forward.',
  'Reach up as if you want to reach the clouds.',
  'Do a dance step: left-right-turn.',
  'Touch your knee with your elbow 8 times.',
  'Walk as if you are sneaking up.',
  'Jump as if you are imagining a jump rope.',
  'Lift one leg and hold for 5 seconds.',
  'Do a “short hand salute” 6 times.',
  'Strike a superhero pose.',
  'Walk forward with a very serious look.',
  'Raise your shoulders up and down 10 times.',
];

export const creativeTasks = [
  'Come up with a new name for Lepra.',
  'Show any animal with gestures.',
  'Make a voice as if you were a cartoon character.',
  'Come up with a mini-legend about luck.',
  'Draw a statue in a funny pose.',
  'Draw a circle in the air with your finger.',
  'Come up with 3 new holidays.',
  'Show an object that is not here.',
  'Come up with a superpower for yourself.',
  "Come up with a winner's cry from the soul.",
  'Describe a non-existent fruit.',
  'Imagine that you are a magician and cast a spell.',
  'Come up with a dance in 3 movements.',
  'Come up with the name of a new planet.',
  'Imagine that you are opening a treasure chest.',
  'Come up with a mascot for a party.',
  'Draw your mood in the air.',
  'Come up with a 1-sentence story.',
  "Draw Lepra's laughter.",
  'Come up with a new color and name for it.',
];

export const oralTasks = [
  'Name three green objects.',
  'Say a word that starts with “L”.',
  'Tell a five-word story.',
  'Make any funny sound.',
  'Compliment the player next to you.',
  'Name your favorite drink.',
  'Come up with a sentence that rhymes.',
  'Describe your mood in one word.',
  'Name any country.',
  'Come up with a joke on the fly.',
  'Explain why Lepra is cool.',
  'Say the calmest sentence you can.',
  'Shout “Luck has come!” as loudly as possible.',
  'Name 3 things you love.',
  'Cheer up your neighbor with a phrase.',
  'Repeat the tongue twister “Lepra cleverly catches lepra”.',
  'Name your favorite color and why.',
  'Come up with a short toast.',
  'Name something funny you saw today.',
  'Say any phrase in a funny voice.',
];
